/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> =
    T extends ColumnType<infer S, infer I, infer U>
        ? ColumnType<S, I | undefined, U>
        : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type InventoryEnumStatus = 'cancel' | 'closed' | 'in_transit' | 'requested';

export type InventoryEnumStockMovement =
    | 'adjustment'
    | 'material_used'
    | 'opening_balance'
    | 'receive'
    | 'return'
    | 'sap_out'
    | 'transfer_in'
    | 'transfer_out';

export type InventoryEnumTransaction = 'accept' | 'request' | 'send';

export type InventoryEnumWoType =
    | 'assurance'
    | 'lintas_arta'
    | 'mtel'
    | 'myrep'
    | 'psb'
    | 'qe/gamas';

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
    [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AuthAccount {
    accessToken: string | null;
    accessTokenExpiresAt: Timestamp | null;
    accountId: string;
    createdAt: Generated<Timestamp>;
    id: string;
    idToken: string | null;
    password: string | null;
    providerId: string;
    refreshToken: string | null;
    refreshTokenExpiresAt: Timestamp | null;
    scope: string | null;
    updatedAt: Timestamp;
    userId: string;
}

export interface AuthUser {
    createdAt: Generated<Timestamp>;
    email: string;
    emailVerified: boolean;
    id: string;
    image: string | null;
    is_active: boolean | null;
    name: string;
    nik: string;
    updatedAt: Generated<Timestamp>;
}

export interface AuthUserMfaDevices {
    created_at: Generated<Timestamp | null>;
    device_fingerprint: string;
    id: Generated<Int8>;
    last_used_at: Timestamp | null;
    trusted_until: Timestamp | null;
    user_id: Int8;
}

export interface AuthVerification {
    createdAt: Generated<Timestamp>;
    expiresAt: Timestamp;
    id: string;
    identifier: string;
    updatedAt: Generated<Timestamp>;
    value: string;
}

export interface CommerceCustomer {
    alamat: string | null;
    created_at: Generated<Timestamp | null>;
    email: string | null;
    id: Generated<number>;
    kontak: string | null;
    kota: string | null;
    nama_customer: string;
    updated_at: Generated<Timestamp | null>;
}

export interface CommerceEvidenMattamTiang {
    created_at: Generated<Timestamp | null>;
    foto_url: string;
    id: Generated<number>;
    kategori: string;
    tiang_id: number | null;
}

export interface CommerceKhsHeaders {
    created_at: Generated<Timestamp | null>;
    customer_id: number;
    effective_from: Generated<Timestamp>;
    effective_to: Timestamp | null;
    id: Generated<number>;
    no_khs: string;
    status: Generated<string>;
    updated_at: Generated<Timestamp | null>;
    uraian: string | null;
    version: Generated<number>;
}

export interface CommerceKhsItems {
    created_at: Generated<Timestamp | null>;
    designator: string;
    harga_jasa: Numeric | null;
    harga_material: Numeric | null;
    id: Generated<number>;
    khs_header_id: number;
    satuan: string;
    spec_details: string | null;
    updated_at: Generated<Timestamp | null>;
    uraian: string;
}

export interface CommerceMattamTiang {
    created_at: Generated<Timestamp | null>;
    created_by: number | null;
    id: Generated<number>;
    jumlah_tiang: number;
    label_odp_real: string;
    latitude_odp: Numeric | null;
    longitude_odp: Numeric | null;
    no_order: string | null;
    panjang_dc: number;
    rfc_material: string | null;
    updated_at: Generated<Timestamp | null>;
}

export interface CommerceMattamTiangDetail {
    created_at: Generated<Timestamp | null>;
    id: Generated<number>;
    latitude: Numeric | null;
    longitude: Numeric | null;
    mattam_tiang_id: number | null;
    nomor_tiang: number;
}

export interface CommercePid {
    customer: string | null;
    fase: string | null;
    id: Generated<number>;
    jenis_eksekusi: string | null;
    nama_project: string | null;
    pm: string | null;
    portofolio: string | null;
    program: string | null;
    project_id: string;
    project_id_sap: string;
    status_project: string | null;
    tanggal_mulai: Timestamp | null;
    tanggal_selesai: Timestamp | null;
    tipe_project: string | null;
}

export interface CommercePortofolio {
    created_at: Generated<Timestamp | null>;
    id: Generated<number>;
    kode_program: string | null;
    portofolio: string;
    program: string;
    uraian: string | null;
}

export interface DataKpro {
    actstart: Timestamp | null;
    amcrew: string | null;
    catatan_teknisi: string | null;
    chief_code: string | null;
    chief_name: string | null;
    created_at: Generated<Timestamp | null>;
    crmordertype: string | null;
    customer_address: string | null;
    customer_name: string | null;
    datecreated: Timestamp | null;
    datel_baru: string | null;
    datel_lama: string | null;
    desc_task: string | null;
    district_baru: string | null;
    district_lama: string | null;
    district_tif: string | null;
    engineermemo: string | null;
    engineermemo_akhir: string | null;
    errorcode: string | null;
    errorcode_akhir: string | null;
    flag_order: string | null;
    flag_pda: string | null;
    flag_wsa: string | null;
    homepassid: string | null;
    id: Generated<Int8>;
    jenis_product: string | null;
    keterangan_pi: string | null;
    laborcode: string | null;
    laborname: string | null;
    lat_inst_ut: number | null;
    lat_retag_ut: number | null;
    latitude_ins: number | null;
    long_inst_ut: number | null;
    long_retag_ut: number | null;
    longitude_ins: number | null;
    measurement: string | null;
    ncli: string | null;
    new_reservationid: string | null;
    no_hp: string | null;
    odp_name: string | null;
    odp_name_ut: string | null;
    ownergroup: string | null;
    package_name: string | null;
    product: string | null;
    regional_baru: string | null;
    regional_lama: string | null;
    schedule_labor: Timestamp | null;
    scorderno: string | null;
    servicenum: string | null;
    status: string | null;
    status_approval: string | null;
    status_odp: string | null;
    status_survey: string | null;
    status_task: string | null;
    statusdate: Timestamp | null;
    sto: string | null;
    suberrorcode: string | null;
    suberrorcode_akhir: string | null;
    tanggal_approval: Timestamp | null;
    territory_tif: string | null;
    tgl_fallout_akhir: Timestamp | null;
    tgl_fallout_awal: Timestamp | null;
    tgl_manja: Timestamp | null;
    tgl_pi_akhir: Timestamp | null;
    tgl_pi_awal: Timestamp | null;
    tiket_id: string | null;
    updated_at: Generated<Timestamp | null>;
    wonum: string;
}

export interface EtlDataKproClean {
    actstart: Timestamp | null;
    amcrew: string | null;
    catatan_teknisi: string | null;
    chief_code: string | null;
    chief_name: string | null;
    crmordertype: string | null;
    customer_address: string | null;
    customer_name: string | null;
    datecreated: Timestamp | null;
    datel_baru: string | null;
    datel_lama: string | null;
    desc_task: string | null;
    district_baru: string | null;
    district_lama: string | null;
    district_tif: string | null;
    engineermemo: string | null;
    engineermemo_akhir: string | null;
    errorcode: string | null;
    errorcode_akhir: string | null;
    flag_order: string | null;
    flag_pda: string | null;
    flag_wsa: string | null;
    homepassid: string | null;
    id: Generated<Int8>;
    jenis_product: string | null;
    job_id: Int8;
    keterangan_pi: string | null;
    laborcode: string | null;
    laborname: string | null;
    lat_inst_ut: Numeric | null;
    lat_retag_ut: Numeric | null;
    latitude_ins: Numeric | null;
    long_inst_ut: Numeric | null;
    long_retag_ut: Numeric | null;
    longitude_ins: Numeric | null;
    measurement: string | null;
    ncli: string | null;
    new_reservationid: string | null;
    no_hp: string | null;
    odp_name: string | null;
    odp_name_ut: string | null;
    ownergroup: string | null;
    package_name: string | null;
    product: string | null;
    regional_baru: string | null;
    regional_lama: string | null;
    schedule_labor: Timestamp | null;
    scorderno: string | null;
    servicenum: string | null;
    status: string | null;
    status_approval: string | null;
    status_odp: string | null;
    status_survey: string | null;
    status_task: string | null;
    statusdate: Timestamp | null;
    sto: string | null;
    suberrorcode: string | null;
    suberrorcode_akhir: string | null;
    tanggal_approval: Timestamp | null;
    territory_tif: string | null;
    tgl_fallout_akhir: Timestamp | null;
    tgl_fallout_awal: Timestamp | null;
    tgl_manja: Timestamp | null;
    tgl_pi_akhir: Timestamp | null;
    tgl_pi_awal: Timestamp | null;
    tiket_id: string | null;
    transformed_at: Generated<Timestamp | null>;
    wonum: string | null;
}

export interface EtlDataRfcMaterialClean {
    description: string | null;
    id: Generated<Int8>;
    job_id: Int8 | null;
    location_of_project: string | null;
    material: string;
    mitra: string | null;
    nama_pemakai: string | null;
    nama_requester: string | null;
    nik_pemakai: string | null;
    no_reservasi: string | null;
    no_rfc: string | null;
    plant: string | null;
    po_number: string | null;
    posting_date: Timestamp | null;
    program: string | null;
    project_id: string | null;
    quantity: Numeric | null;
    regional: string | null;
    requester: string | null;
    satuan: string | null;
    transformed_at: Generated<Timestamp | null>;
    type: string | null;
    wbs_element: string | null;
    witel: string | null;
}

export interface EtlDataSapFinanceTreeClean {
    actual_cost: Numeric | null;
    actual_revenue: Numeric | null;
    basic_fin_date: Timestamp | null;
    budget: Numeric | null;
    cost_commitment: Numeric | null;
    description: string | null;
    id: Generated<Int8>;
    job_id: Int8 | null;
    level: number;
    parent_id: Int8 | null;
    parent_title: string | null;
    path: string | null;
    proj_cost_plan: Numeric | null;
    release: Numeric | null;
    start_date: Timestamp | null;
    status: string | null;
    title: string;
    transformed_at: Generated<Timestamp | null>;
    user_field: string | null;
}

export interface EtlImportJobs {
    created_at: Generated<Timestamp | null>;
    error_rows: Generated<number | null>;
    file_name: string;
    file_size: Int8 | null;
    finished_at: Timestamp | null;
    id: Generated<Int8>;
    processed_rows: Generated<number | null>;
    started_at: Timestamp | null;
    status: Generated<string | null>;
    success_rows: Generated<number | null>;
    total_rows: number | null;
}

export interface EtlStagingDataKproRaw {
    id: Generated<Int8>;
    imported_at: Generated<Timestamp | null>;
    job_id: Int8 | null;
    raw_data: Json;
}

export interface EtlStagingDataRfcMaterialRaw {
    id: Generated<Int8>;
    imported_at: Generated<Timestamp | null>;
    job_id: Int8 | null;
    raw_data: Json;
}

export interface EtlStagingDataSapFinanceTreeRaw {
    id: Generated<Int8>;
    imported_at: Generated<Timestamp | null>;
    job_id: Int8 | null;
    raw_data: Json;
}

export interface EtlUploadLogs {
    created_at: Generated<Timestamp | null>;
    id: Generated<Int8>;
    last_updated_at: Timestamp | null;
    table_name: string | null;
    updated_by: number | null;
}

export interface FinanceCostStructure {
    cogs: Numeric;
    created_at: Generated<Timestamp | null>;
    depresiasi: Numeric;
    gross_profit: Numeric;
    id: Generated<Int8>;
    kode_program: string;
    material_non_stock: Numeric;
    material_stock: Numeric;
    mitra_jasa: Numeric;
    operasional: Numeric;
    sewa: Numeric;
    tenaga_kerja: Numeric;
    tipe_cost_structure: string;
}

export interface FinanceSapFinanceTree {
    actual_cost: Generated<Numeric | null>;
    actual_revenue: Generated<Numeric | null>;
    budget: Generated<Numeric | null>;
    cost_commitment: Generated<Numeric | null>;
    created_at: Generated<Timestamp | null>;
    description: string | null;
    id: Generated<Int8>;
    level: number;
    parent_id: Int8 | null;
    path: string | null;
    proj_cost_plan: Generated<Numeric | null>;
    release: Generated<Numeric | null>;
    status: string | null;
    title: string;
    updated_at: Generated<Timestamp | null>;
    user_field: string | null;
}

export interface HrBizpart {
    bizpart: string;
    id: Generated<number>;
}

export interface HrBranches {
    area: string;
    branch: string;
    id: Generated<number>;
    regional: string;
    service_area: string;
}

export interface HrEmployees {
    bizpart_id: number | null;
    branch_id: number | null;
    created_at: Generated<Timestamp | null>;
    id: Generated<Int8>;
    level_id: number | null;
    mitra_id: number | null;
    nama: string | null;
    nik: string | null;
    position_id: number | null;
    status: string | null;
}

export interface HrLevels {
    id: Generated<number>;
    level_name: string;
}

export interface HrMitras {
    id: Generated<number>;
    mitra_name: string | null;
}

export interface HrPositions {
    id: Generated<number>;
    position_name: string | null;
}

export interface HrStoToSa {
    branch_id: number;
    id: Generated<number>;
    sto: string;
}

export interface HrTechnicians {
    branch_id: number | null;
    created_at: Generated<Timestamp>;
    created_by: string | null;
    id: Generated<Int8>;
    is_active: Generated<boolean>;
    level_id: number | null;
    mitra_id: number | null;
    name: string;
    nik: string;
}

export interface HrWitel {
    id: Generated<number>;
    kode_witel: string | null;
    nama_witel: string;
}

export interface InventoryInoutTagHeader {
    accept_id: string | null;
    accept_time: Timestamp | null;
    created_by: string | null;
    end_status: InventoryEnumStatus;
    from_wh_id: number | null;
    id: Generated<Int8>;
    id_trx: string;
    nik_send: string | null;
    notes: string | null;
    request_id: string | null;
    request_time: Generated<Timestamp>;
    send_id: string | null;
    send_time: Timestamp | null;
    to_wh_id: number | null;
}

export interface InventoryInoutTagItems {
    action: InventoryEnumTransaction;
    action_id: string;
    created_at: Generated<Timestamp>;
    designator_id: Int8;
    header_id: Int8;
    id: Generated<Int8>;
    qty: number;
    unit_price: Numeric | null;
}

export interface InventoryMasWh {
    branch: string;
    check_stock: boolean | null;
    created_at: Generated<Timestamp>;
    id: Generated<number>;
    intls: string;
    name: string;
    /** NIK staff PIC utama yang bertanggung jawab atas gudang ini */
    pic_1: string | null;
    /** NIK staff PIC kedua untuk gudang ini */
    pic_2: string | null;
    updated_at: Generated<Timestamp>;
}

export interface InventoryMaterialRekonsiliasi {
    created_at: Generated<Timestamp | null>;
    id: Generated<Int8>;
    sn_ont: string;
    wonum_id: number;
}

export interface InventoryMaterialRekonsiliasiActualList {
    created_at: Generated<Timestamp | null>;
    id: Generated<Int8>;
    material_id: number;
    material_rekonsiliasi_id: Int8;
    quantity: Numeric;
    reservation_id: number | null;
    satuan: string | null;
}

export interface InventoryMaterialRekonsiliasiSources {
    created_at: Generated<Timestamp | null>;
    id: Generated<Int8>;
    material_rekonsiliasi_id: Int8;
    reservation_id: number;
}

export interface InventoryMaterialReservationItems {
    created_at: Generated<Timestamp | null>;
    id: Generated<Int8>;
    material: string;
    quantity: Numeric | null;
    reservation_id: Int8;
    satuan: string | null;
}

export interface InventoryMaterialReservations {
    created_at: Generated<Timestamp | null>;
    description: string | null;
    id: Generated<number>;
    location_of_project: string | null;
    mitra: string | null;
    nama_pemakai: string | null;
    nama_requester: string | null;
    nik_pemakai: string | null;
    no_reservasi: string | null;
    no_rfc: string;
    plant: string | null;
    po_number: string | null;
    posting_date: Timestamp | null;
    program: string | null;
    project_id: string | null;
    regional: string | null;
    requester: string | null;
    type: string | null;
    wbs_element: string | null;
    witel: string | null;
}

export interface InventoryMaterials {
    code: string | null;
    created_at: Generated<Timestamp>;
    description: string | null;
    id: Generated<number>;
    unit: string;
    updated_at: Generated<Timestamp>;
}

export interface InventoryReturnMaterialHeader {
    accept_id: string | null;
    accept_time: Timestamp | null;
    created_at: Generated<Timestamp | null>;
    created_by: string | null;
    end_status: Generated<string>;
    id: Generated<Int8>;
    id_trx: string;
    nik_teknisi: string;
    notes: string | null;
    sap_out_id: Int8;
    warehouse_id: Int8;
}

export interface InventoryReturnMaterialItems {
    designator_id: Int8;
    header_id: Int8;
    id: Generated<Int8>;
    qty: number;
    sap_out_item_id: Int8;
}

export interface InventorySapOutHeader {
    created_by: string | null;
    end_status: string | null;
    id: Generated<Int8>;
    id_reservasi: string | null;
    id_trx: string;
    name_sa: string;
    nik_teknisi: string;
    request_id: string;
    request_time: Generated<Timestamp>;
    sap_number: string | null;
    sap_time: Timestamp | null;
    /**
     * Warehouse asal pengeluaran SAP. Wajib diisi agar stock_balance bisa dikurangi.
     */
    warehouse_id: number | null;
}

export interface InventorySapOutItems {
    created_at: Generated<Timestamp>;
    designator_id: Int8;
    header_id: Int8;
    id: Generated<Int8>;
    qty_req: number;
    qty_used: number | null;
    unit_price: Numeric | null;
}

export interface InventoryStockBalance {
    designator_id: number;
    id: Generated<Int8>;
    qty_stock: Generated<number>;
    updated_at: Generated<Timestamp>;
    warehouse_id: number;
}

export interface InventoryStockMovement {
    created_at: Generated<Timestamp>;
    created_by: string | null;
    designator_id: number;
    id: Generated<Int8>;
    movement_type: InventoryEnumStockMovement;
    notes: string | null;
    qty_after: Generated<number>;
    qty_delta: number;
    reference_trx: string | null;
    warehouse_id: number;
}

export interface InventoryStockPolicy {
    id: Generated<Int8>;
    warehouse_id: number;
    designator_id: number;
    min_qty: Generated<number>;
    max_qty: Generated<number>;
    average_demand_weekly: Generated<string>;
    lead_time_weeks: Generated<number>;
    safety_stock_pct: Generated<string>;
    updated_at: Generated<Timestamp | null>;
}

export interface InventoryTransactionUsedHeader {
    created_at: Generated<Timestamp>;
    created_by: string | null;
    id: Generated<Int8>;
    id_trx: string | null;
    name_sa: string;
    name_wh: string;
    nik_teknisi: string;
    sap_out_id: Int8;
    wo_number: string;
    wo_type: InventoryEnumWoType;
}

export interface InventoryTransactionUsedItem {
    created_at: Generated<Timestamp>;
    designator_id: Int8;
    id: Generated<Int8>;
    qty: number;
    unit_price: Numeric | null;
    used_id: Int8;
    notes: string | null;
}

export interface InventoryVendorTracking {
    cost: Numeric | null;
    created_at: Generated<Timestamp>;
    header_id: Int8;
    id: Generated<Int8>;
    name_vendor: string | null;
}

export interface NteInventoryItems {
    created_at: Generated<Timestamp>;
    current_location_id: Int8;
    id: Generated<Int8>;
    installation_date: Timestamp | null;
    internet_number: string | null;
    inventory_model_id: Int8;
    mac_address: string | null;
    serial_number: string;
    status_id: Int8;
    updated_at: Generated<Timestamp>;
}

export interface NteInventoryModels {
    description: string | null;
    id: Generated<Int8>;
    inventory_type_id: Int8;
    is_active: Generated<boolean>;
    model: string;
    vendor: string;
}

export interface NteInventoryTransactionItems {
    id: Generated<Int8>;
    inventory_item_id: Int8;
    new_location_id: Int8;
    new_status_id: Int8;
    previous_location_id: Int8 | null;
    previous_status_id: Int8 | null;
    transaction_id: Int8;
}

export interface NteInventoryTransactions {
    created_at: Generated<Timestamp>;
    created_by: Int8;
    destination_location_id: Int8 | null;
    document_number: string;
    id: Generated<Int8>;
    remarks: string | null;
    source_location_id: Int8 | null;
    transaction_date: Generated<Timestamp>;
    transaction_type: string;
}

export interface NteInventoryTypes {
    code: string;
    has_mac_address: Generated<boolean>;
    has_serial_number: Generated<boolean>;
    id: Generated<Int8>;
    name: string;
}

export interface NteLocations {
    code: string;
    created_at: Generated<Timestamp>;
    id: Generated<Int8>;
    is_active: Generated<boolean>;
    location_type: string;
    name: string;
    reference_id: Int8 | null;
    updated_at: Generated<Timestamp>;
}

export interface NteStatuses {
    code: string;
    description: string | null;
    id: Generated<Int8>;
    name: string;
}

export interface ProcurementVendor {
    alamat: string | null;
    created_at: Generated<Timestamp | null>;
    id: Generated<number>;
    kontak: string | null;
    nama_vendor: string;
}

export interface ProjectApprovalAssignments {
    approval_status: Generated<string | null>;
    assigned_at: Generated<Timestamp | null>;
    assigned_by_nik: string | null;
    assigned_to_name: string | null;
    assigned_to_nik: string;
    boq_id: Int8 | null;
    id: Generated<number>;
    is_active: Generated<boolean | null>;
    lop_id: Int8 | null;
    notes: string | null;
    service_area_id: number | null;
}

export interface ProjectApprovalLogs {
    action: string;
    boq_id: Int8 | null;
    created_at: Generated<Timestamp | null>;
    id: Generated<number>;
    lop_id: Int8 | null;
    notes: string | null;
    performed_by_name: string | null;
    performed_by_nik: string | null;
}

export interface ProjectBoqEvidences {
    approved_at: Timestamp | null;
    approved_by: number | null;
    evidence_type: string;
    file_name: string | null;
    file_size: number | null;
    file_url: string;
    id: Generated<Int8>;
    is_deleted: Generated<boolean | null>;
    mime_type: string | null;
    real_item_id: number;
    uploaded_at: Generated<Timestamp | null>;
    uploaded_by: number | null;
    uraian: string | null;
}

export interface ProjectListOfLop {
    approved_at: Timestamp | null;
    approved_by: number | null;
    bulan: number;
    created_at: Generated<Timestamp | null>;
    created_by: number | null;
    customer_id: number;
    id: Generated<Int8>;
    ihld_id: number | null;
    nomor_aiss: number | null;
    pid_id: number | null;
    program_id: number;
    progres_pekerjaan_id: number;
    project_code: Generated<string | null>;
    sa_branch_id: number;
    status: Generated<string>;
    tahun: number;
    tiket_qe: string | null;
    type_pekerjaan: string;
    updated_at: Generated<Timestamp | null>;
    uraian_pekerjaan: string;
    vendor_id: number | null;
    witel_id: number;
}

export interface ProjectLopBoqHeaders {
    approved_at: Timestamp | null;
    approved_by: number | null;
    created_at: Generated<Timestamp | null>;
    created_by: number | null;
    id: Generated<Int8>;
    lop_id: Int8;
    notes: string | null;
    status: Generated<string>;
    updated_at: Generated<Timestamp | null>;
    version: Generated<number>;
}

export interface ProjectLopBoqItems {
    boq_id: number;
    created_at: Generated<Timestamp | null>;
    designator: string;
    harga_jasa: Numeric | null;
    harga_material: Numeric | null;
    has_evidence: Generated<boolean | null>;
    id: Generated<Int8>;
    khs_item_id: number;
    notes: string | null;
    qty_plan: Numeric;
    satuan: string | null;
    subtotal_plan_jasa: Generated<Numeric | null>;
    subtotal_plan_material: Generated<Numeric | null>;
    updated_at: Generated<Timestamp | null>;
    uraian: string;
}

export interface ProjectLopBoqRealItems {
    boq_item_id: number | null;
    created_at: Generated<Timestamp | null>;
    designator: string | null;
    harga_override: Generated<boolean | null>;
    id: Generated<Int8>;
    is_extra_item: Generated<boolean | null>;
    notes: string | null;
    override_reason: string | null;
    plan_harga_jasa: Numeric | null;
    plan_harga_material: Numeric | null;
    plan_qty: Numeric | null;
    plan_subtotal_jasa: Generated<Numeric | null>;
    plan_subtotal_material: Generated<Numeric | null>;
    qty_real: Numeric;
    real_harga_jasa: Numeric;
    real_harga_material: Numeric;
    realization_id: number;
    satuan: string | null;
    subtotal_real_jasa: Generated<Numeric | null>;
    subtotal_real_material: Generated<Numeric | null>;
    updated_at: Generated<Timestamp | null>;
    uraian: string | null;
}

export interface ProjectLopBoqRealizations {
    approved_at: Timestamp | null;
    approved_by: number | null;
    boq_header_id: number;
    created_at: Generated<Timestamp | null>;
    created_by: number | null;
    id: Generated<number>;
    lop_id: number;
    notes: string | null;
    status: Generated<string>;
    updated_at: Generated<Timestamp | null>;
}

export interface ProjectProgresPekerjaan {
    created_at: Generated<Timestamp | null>;
    id: number;
    is_final: Generated<boolean | null>;
    kode: string;
    nama: string;
    urutan: number;
}

export interface ProjectWorkflowApprovalLogs {
    approval_order: number;
    approval_status: Generated<string | null>;
    approved_at: Timestamp | null;
    approved_by: number | null;
    id: Generated<Int8>;
    lop_id: number;
    notes: string | null;
    role_name: string;
    status_id: number;
}

export interface ProjectWorkflowApprovals {
    approval_order: number;
    created_at: Generated<Timestamp | null>;
    entity_type: Generated<string | null>;
    id: Generated<number>;
    is_mandatory: Generated<boolean | null>;
    level_id: number | null;
    level_name: string | null;
    role_name: string;
    to_status_id: number;
}

export interface ProjectWorkflowTransitions {
    created_at: Generated<Timestamp | null>;
    from_status_id: number;
    id: Generated<number>;
    is_active: Generated<boolean | null>;
    to_status_id: number;
    transition_name: string | null;
}

export interface UploadLogs {
    id: Generated<Int8>;
    last_updated_at: Generated<Timestamp | null>;
    table_name: string | null;
    updated_by: number | null;
}

export interface DB {
    'auth.account': AuthAccount;
    'auth.user': AuthUser;
    'auth.user_mfa_devices': AuthUserMfaDevices;
    'auth.verification': AuthVerification;
    'commerce.customer': CommerceCustomer;
    'commerce.eviden_mattam_tiang': CommerceEvidenMattamTiang;
    'commerce.khs_headers': CommerceKhsHeaders;
    'commerce.khs_items': CommerceKhsItems;
    'commerce.mattam_tiang': CommerceMattamTiang;
    'commerce.mattam_tiang_detail': CommerceMattamTiangDetail;
    'commerce.pid': CommercePid;
    'commerce.portofolio': CommercePortofolio;
    data_kpro: DataKpro;
    'etl.data_kpro_clean': EtlDataKproClean;
    'etl.data_rfc_material_clean': EtlDataRfcMaterialClean;
    'etl.data_sap_finance_tree_clean': EtlDataSapFinanceTreeClean;
    'etl.import_jobs': EtlImportJobs;
    'etl.staging_data_kpro_raw': EtlStagingDataKproRaw;
    'etl.staging_data_rfc_material_raw': EtlStagingDataRfcMaterialRaw;
    'etl.staging_data_sap_finance_tree_raw': EtlStagingDataSapFinanceTreeRaw;
    'etl.upload_logs': EtlUploadLogs;
    'finance.cost_structure': FinanceCostStructure;
    'finance.sap_finance_tree': FinanceSapFinanceTree;
    'hr.bizpart': HrBizpart;
    'hr.branches': HrBranches;
    'hr.employees': HrEmployees;
    'hr.levels': HrLevels;
    'hr.mitras': HrMitras;
    'hr.positions': HrPositions;
    'hr.sto_to_sa': HrStoToSa;
    'hr.technicians': HrTechnicians;
    'hr.witel': HrWitel;
    'inventory.inout_tag_header': InventoryInoutTagHeader;
    'inventory.inout_tag_items': InventoryInoutTagItems;
    'inventory.mas_wh': InventoryMasWh;
    'inventory.material_rekonsiliasi': InventoryMaterialRekonsiliasi;
    'inventory.material_rekonsiliasi_actual_list': InventoryMaterialRekonsiliasiActualList;
    'inventory.material_rekonsiliasi_sources': InventoryMaterialRekonsiliasiSources;
    'inventory.material_reservation_items': InventoryMaterialReservationItems;
    'inventory.material_reservations': InventoryMaterialReservations;
    'inventory.materials': InventoryMaterials;
    'inventory.return_material_header': InventoryReturnMaterialHeader;
    'inventory.return_material_items': InventoryReturnMaterialItems;
    'inventory.sap_out_header': InventorySapOutHeader;
    'inventory.sap_out_items': InventorySapOutItems;
    'inventory.stock_balance': InventoryStockBalance;
    'inventory.stock_movement': InventoryStockMovement;
    'inventory.stock_policy': InventoryStockPolicy;
    'inventory.transaction_used_header': InventoryTransactionUsedHeader;
    'inventory.transaction_used_item': InventoryTransactionUsedItem;
    'inventory.vendor_tracking': InventoryVendorTracking;
    'nte.inventory_items': NteInventoryItems;
    'nte.inventory_models': NteInventoryModels;
    'nte.inventory_transaction_items': NteInventoryTransactionItems;
    'nte.inventory_transactions': NteInventoryTransactions;
    'nte.inventory_types': NteInventoryTypes;
    'nte.locations': NteLocations;
    'nte.statuses': NteStatuses;
    'procurement.vendor': ProcurementVendor;
    'project.approval_assignments': ProjectApprovalAssignments;
    'project.approval_logs': ProjectApprovalLogs;
    'project.boq_evidences': ProjectBoqEvidences;
    'project.list_of_lop': ProjectListOfLop;
    'project.lop_boq_headers': ProjectLopBoqHeaders;
    'project.lop_boq_items': ProjectLopBoqItems;
    'project.lop_boq_real_items': ProjectLopBoqRealItems;
    'project.lop_boq_realizations': ProjectLopBoqRealizations;
    'project.progres_pekerjaan': ProjectProgresPekerjaan;
    'project.workflow_approval_logs': ProjectWorkflowApprovalLogs;
    'project.workflow_approvals': ProjectWorkflowApprovals;
    'project.workflow_transitions': ProjectWorkflowTransitions;
    upload_logs: UploadLogs;
}
