import { Kysely, PostgresDialect } from 'kysely';
import { Pool } from 'pg';
import type { DB } from './database.types';

const dialect = new PostgresDialect({
    pool: new Pool({
        connectionString: process.env.DATABASE_URL,
        max: 10,
    }),
});

// Database interface is generated by kysely-codegen
export const db = new Kysely<DB>({
    dialect,
});
